### ISSUE TITLE
Question about test

### ISSUE THREAD

**Issue by zhangbaijin** [AndresPMD/GCN_classification#1]
Thanks for you contribution! It is amazing. When i run test.py there is a problem.
`ValueError: cannot reshape array of size 318242784 into shape (18488,36,2048)
`
and my command is `python test.py bottles --model fullGCN_bboxes --ocr google_ocr --embedding fasttext --max_textual 15 --max_visual 36 --projection_layer mean --fusion concat 
`

**Comment by zhangbaijin** [comment]
What's in the folder single_features_bottles??

**Comment by AndresPMD** [comment]
Hello @zhangbaijin,

Have you downloaded all the files provided?
Can you confirm if you are using the correct dependencies and versions?

Additionally, can you provide the log on which is this error coming from?

**Comment by IwenLeeO** [comment]
sorry to bother, i have same problem, when i try to test the model. could you please tell me how to solve it and what is should be in single_feature_bottles folder?

**Comment by AndresPMD** [comment]
Hello,
I edited the test.py file to extract some features for visualization purposes and now it contains a bug that needs to be solved.

Meanwhile, you can test the model by running the train.py script with the option --test True. Which has the same functionality and evaluation as test.py. Example:

python train.py bottles --batch_size 64 --model fullGCN_bboxes --ocr google_ocr --embedding fasttext --max_textual 15 --max_visual 36 --projection_layer mean --fusion concat --split 2 --save_weights False --load ../best/bottles_fullGCN_bboxes_fasttext_google_ocr_concat_mean_split2/checkpoint_bottles.weights --test True


Sorry for the inconvenience. I will work on the test.py bug as soon as I have time after focusing on other projects.
