### ISSUE TITLE
a error "images_with_text.json"  happen

### ISSUE THREAD

**Issue by zpfinley** [AndresPMD/GCN_classification#6]
Thank you for your codes, it is a good work! When I run the performance.py, a error "images_with_text.json"  happen. But I find that this file not in the goolge share and not find the Code that Generate this file. How to get or Generate  this file ?
Thank you very much!

**Comment by AndresPMD** [comment]
@zpfinley

This JSON file contains a subset of the test set that includes images with or without scene text. This file can be generated by running any OCR engine to detect whether scene text is found or not (and the results may change depending on the accuracy of the OCR), however, it is just to evaluate the performance of the model on a specific setting.
